

stg:
  DOWNLOAD_BUCKET_NAME: stg-econet-plateau-download-bucket
  APPLICATION_BUCKET_NAME: stg-econet-plateau.net
  CLOUDFRONT_CERTIFICATE_ARN: arn:aws:acm:us-east-1:617648548008:certificate/64bd8242-57b2-4cd5-a104-6e77fb72900d
  APPLICATION_CUSTOM_DOMAIN_NAME: stg.econet-plateau.net
  HOSTED_ZONE_ID_DOMAIN: Z051923034SC01Y6TVKQ1
  TILES_BUCKET_NAME: econet-plateau-tiles-bucket